apiVersion: v1
kind: Secret
metadata:
  name: app1-java-react-secrets
  labels:
    {{- include "app1.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | default .Values.postgres.password | quote }}
{{- if .Values.pgadmin.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: app1-java-react-pgadmin-secrets
  labels:
    {{- include "app1.labels" . | nindent 4 }}
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.secrets.pgadminEmail | default .Values.pgadmin.email | quote }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.secrets.pgadminPassword | default .Values.pgadmin.password | quote }}
{{- end }}
