{{- if eq .Values.env "dev" }}
apiVersion: v1
kind: Service
metadata:
  name: app1-java-react-frontend
  labels:
    {{- include "app1.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "app1.name" . }}
    component: frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app1-java-react-frontend-dev
  labels:
    {{- include "app1.labels" . | nindent 4 }}
spec:
  serviceName: app1-java-react-frontend
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app1.name" . }}
      component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app1.name" . }}
        component: frontend
    spec:
      securityContext:
        fsGroup: 10001
      initContainers:
        - name: prepare-dev-env
          image: {{ index .Values.werf.image "frontend-dev" }}
          command: ["sh", "-c", "cd /home/app/prepare-scripts && sudo ./init-dev-env.sh"]
          volumeMounts:
            - { name: workspace, mountPath: /workspace }
            - { name: homeapp, mountPath: /home/app/homeapp }
            - { name: id-rsa-vcs, mountPath: /home/app/.ssh/id_rsa, subPath: id_rsa }
      containers:
        - name: frontend
          image: {{ index .Values.werf.image "frontend-dev" }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - { name: workspace, mountPath: /workspace }
            - { name: homeapp, mountPath: /home/app/homeapp }
            - { name: id-rsa-vcs, mountPath: /home/app/.ssh/id_rsa, subPath: id_rsa }
      volumes:
        - name: id-rsa-vcs
          secret:
            secretName: id-rsa-vcs
            defaultMode: 0600
  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.dev.storageClass }}
        resources:
          requests:
            storage: {{ .Values.dev.workspaceSize }}
    - metadata:
        name: homeapp
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.dev.storageClass }}
        resources:
          requests:
            storage: {{ .Values.dev.homeappSize }}
{{- end }}
