{{- if eq .Values.env "dev" }}
apiVersion: v1
kind: Secret
metadata:
  name: id-rsa-vcs
  labels:
    {{- include "app2.labels" . | nindent 4 }}
type: Opaque
data:
  id_rsa: {{ .Files.Get "tmp/id_rsa-vcs" | b64enc | quote }}
{{- end }}
